---
title: Team
---

## Professor Shanthakumar Wilson Rajaratnam

[Prof. Rajaratnam](https://research.monash.edu/en/persons/shanthakumar-wilson-rajaratnam) 
is the principal investigator of the CLASS study. 
His research program aims to investigate the role of the
internal biological clock in the regulation of the sleep-wake cycle,
and how disruption of the clock leads to sleep disorders and other
physiological consequences (for example, in shift workers). His group
develops novel treatment approaches for sleep disorders that are
caused by biological clock disruption. These include light and
melatonin treatments. He is also investigating the contribution of
sleep disturbances and fatigue to mood disorders and impaired
cognition in clinical populations. 

## Dr. Bei Bei

[Dr. Bei](https://research.monash.edu/en/persons/bei-bei)
is a chief investigator on the CLASS study.
She is a Clinical Psychologist and sleep researcher. She is
interested the individual differences in sleep-wake behaviours, the
relationship between sleep and mental health, and psychological
interventions for better sleep. Her clinical work has focused on mood,
anxiety, and sleep disorders in adult, adolescent, and perinatal
populations. 

## Associate Professor Sean Cain

[A/Prof. Cain](https://research.monash.edu/en/persons/sean-cain) 
is a collaborator on the CLASS study.
His research interests include sex differences in circadian rhythms
and sleep, rhythms in cognitive performance, the neurobiology of
nonphotic input to the biological clock, and the effect of aging on
circadian function and cognition.
Currently, he is examining circadian rhythms and sleep in human
subjects. His primary focus is the examination of the relative
influences of the circadian clock and sleep-wake homeotstat on
cognitive function. This work involves examining how acute and chronic
sleep loss affects different aspects of cognition across the 24-hour
biological day. His work also focuses on sex differences in circadian
rhythms and sleep. He has recently found that the habitual sleep of
women is advanced, relative to men. This advanced timing may make
women more vulnerable sleep disruption and insomnia. 

## Professor Mary Carskadon

[Prof. Carskadon](https://vivo.brown.edu/display/mcarskad) 
is an international investigator on the CLASS study.
Prof. Carskadon's current research includes an evaluation of how sleep
and circadian timing influence smell, taste, food choices, and food
consumption in overweight and normal weight teens and development of
“smart lighting” to improve academic outcomes in secondary school
students. Her team is also investigating the impact of serial nights
of alcohol use in adults on sleep and next-day cognitive performance.
Proposed new projects seek to (1) perform field and laboratory studies
of caffeine's effect on sleep and circadian phase in early
adolescence; (2) measure DNA methylation and genotype with
observational phenotyping and experimental interventions in young
adults and test genes identified in a model organism, C. elegans; and
(3) measure sleep and asthma disparities in urban children; (4)
examine the role of sleep and circadian timing of salivary amylase in
food choices; (5) assess how sleep duration impacts immune balance in
inner-city children with asthma; (6) evaluate methods to deliver
smart-lighting to improve wellness in older adults. 

## Associate Professor Elizabeth B. Klerman

[A/Prof. Klerman](https://sleep.med.harvard.edu/people/faculty/225/Elizabeth+B+Klerman+MD+PhD) 
is an international investigator on the CLASS study.
Her current research focuses on the areas of: (1) the interaction of
endocrine, circadian and sleep rhythms in normal and pathological
states (2) mathematical modeling of sleep, circadian system and
markers of its function.
Dr. Klerman is Director of the Analytic Modeling Unit within the
Division of Sleep Medicine at BWH. She collaborates with investigators
from other Divisions to apply the principles of circadian rhythms
research to the study of human physiology and pathophysiology. Members
of the Analytic and Modeling Unit systematically and mathematically
explore many aspects of the sleep and circadian rhythms. The results
have implications for the design and analysis of future circadian
experiments as well as reinterpretation of earlier studies. This work
is part of a cycle of experimental work- mathematical modeling and
predictions- experimental work. 

## Associate Professor Steven W. Lockley
[A/Prof. Lockley](https://sleep.med.harvard.edu/people/faculty/163/Steven+W+Lockley+PhD)
is an international investigator on the CLASS study.
The Circadian Physiology Program focuses on basic and applied aspects
of human circadian biology. Their translational approach includes use of
a range of techniques including epidemiology, field-based
physiological studies and inpatient intensive physiological
monitoring. They have a particular interest in human circadian
photoreception and the effects of light on the circadian pacemaker and
other non-image forming responses. Their studies include investigations
of the effects of timing, duration, intensity and wavelength of light
exposure on circadian resetting, melatonin suppression and the acute
alerting effects of light. They also study visually impaired individuals
under field and laboratory conditions to examine the effects of the
severity and type of blindness on circadian photoreception, the
periodicity of the circadian pacemaker and development of circadian
rhythm sleep disorders. These basic studies have led to the
development of novel therapeutic strategies to treat non-24-hour sleep
wake disorder, Advanced- and Delayed Sleep Phase Syndrome with
appropriately-timed melatonin administration in blind patients. They
have also recently begun to examine the role of visual impairment on
endocrinology and breast cancer risk in blind women. 

## Dr. Andrew Phillips

[Dr. Phillips](https://research.monash.edu/en/persons/andrew-phillips) 
is a collaborator on the CLASS study.
Dr. Phillips is a Senior Lecturer within the Monash Institute of
Cognitive and Clinical Neurosciences in the School of Psychological
Sciences. His research vision is to understand the biology, behaviour,
and functions of sleep and circadian rhythms through physiologically
based modelling. He has developed mathematical models and health-based
metrics that are widely used in the sleep and circadian fields. His
work is closely integrated with experiments, so that model predictions
can be tested and so that additional insights can be gleaned from
data.

## Julia Stone



## Dr. Joshua F. Wiley

[Dr. Wiley](https://research.monash.edu/en/persons/joshua-wiley)
is a chief investigator on the CLASS study.
He is a behavioural medicine researcher currently at Monash
University. His research includes basic science and applied
intervention work. In basic science, his work focuses on understanding
the daily and longitudinal dynamics of sleep, psychosocial factors and
health. His intervention research focuses on accessible and feasible
sleep/behavioural and emotion regulation interventions with potential
for broad dissemination.
